# Generated by Django 2.1.1 on 2018-10-01 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0016_auto_20181001_0203'),
    ]

    operations = [
    ]
